apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: ghcr.io/sdb-devops/backstage-demo
          imagePullPolicy: Always
          ports:
            - containerPort: 7007
          env:
            - name: NODE_ENV
              value: "production"
            - name: K8S_CLUSTER_URL
              value: "https://136.115.235.197:6443"
            - name: K8S_SA_TOKEN          # ← app-config.yaml 里的 ${K8S_SA_TOKEN}
              valueFrom:
                secretKeyRef:
                  name: backstage-secrets
                  key: k8s-sa-token
            - name: AUTH_GITHUB_CLIENT_ID          # ← app-config.yaml 里的 ${K8S_SA_TOKEN}
              value: Ov23lixpDapPXde0wVGK
            - name: AUTH_GITHUB_CLIENT_SECRET          # ← app-config.yaml 里的 ${K8S_SA_TOKEN}
              valueFrom:
                secretKeyRef:
                  name: backstage-github-secrets
                  key: AUTH_GITHUB_CLIENT_SECRET