apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: ghcr.io/sdb-devops/backstage-demo:370955ab79fd2a2c926b4a9c5ba2a17de1246540
          imagePullPolicy: Always
          ports:
            - containerPort: 7007
          env:
            - name: NODE_ENV
              value: "production"