apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/sdb-devops/backstage-demo
    newTag: a7223bbfcd82e3b70297edddb78355929566eec5