apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/sdb-devops/backstage-demo
    newTag: 90d3ebf5b0daa57af94122e0723ecde292d86b05