apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/sdb-devops/backstage-demo
    newTag: faada77d629dfec553dc53fcf812d06e522479d1